[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = []

[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start:prod'

[variables]
NPM_CONFIG_PRODUCTION = 'false'
